CREATE TABLE IF NOT EXISTS notification (
    id UUID PRIMARY KEY NOT NULL,
    type VARCHAR(10) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message VARCHAR(1024) NOT NULL,
    link VARCHAR(1024),
    read BOOLEAN NOT NULL
);
